- name: Get token from step-ca for host
  delegate_to: localhost
  become: no

  command: step ca token --ssh --host {{ hostname }}
  register: token

- name: Template cloud-init to nodes
  template:
    src: cloud-init.sh
    dest: /var/lib/vz/snippets/cloud-init-{{ hostname }}.sh

- name: Create VM
  proxmox_kvm:
    api_host: pve-0.engiqueer.net
    api_user: root@pam
    api_token_id: ansible
    api_token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
    clone: debian12-template
    name: "{{ hostname }}"
    node: "{{ node }}"
  become: no
  delegate_to: localhost
  register: kvm

- name: Set cicustom
  shell: qm set {{ kvm.vmid }} --cicustom "vendor=local:snippets/cloud-init-{{ hostname }}.sh"
  when: ansible_host == node and kvm.changed
